### ISSUE TITLE
AutoNav 中可以支持设置 文档的根目录么？ 比如 文档统一在【根目录/src】下。  srcDir: "src"？

### ISSUE THREAD

**Issue by markyun** [Xaviw/vite-plugin-vitepress-auto-nav#1]
AutoNav({       
                               srcDir: "src",
				pattern: ‘’，
				settings: {},
				itemsSetting: {  },
				useArticleTitle: true
			}),

AutoNav中可以设置文档所在的根目录么？ 比如 文档统一在  src 下。
 srcDir: "src"

**Comment by Xaviw** [comment]
插件默认就是读取的 `VitePress` 中 `srcDir` 配置作为匹配目录， `pattern` 参数的注释有提到

**Comment by markyun** [comment]
@Xaviw  我用你的仓库测试过了，如果设置了 srcDir: "src" 值，编译出来的项目，没有 头部菜单 和左侧菜单。

**Comment by markyun** [comment]
如图只剩下 设置的  src 目录了

![image](https://github.com/Xaviw/vite-plugin-vitepress-auto-nav/assets/2833137/83208de0-01fa-44e8-ade4-61bbfeb2704e)

![Uploading image.png…]()

**Comment by Xaviw** [comment]
确实存在相关问题，感谢提出，我会尝试解决

**Comment by markyun** [comment]
> 确实存在相关问题，感谢提出，我会尝试解决

感觉是传值的问题？ 没有在插件中 拿到 srcDir 的值？

**Comment by markyun** [comment]
> 确实存在相关问题，感谢提出，我会尝试解决

有思路了么？

**Comment by Xaviw** [comment]
`V2.2.0` 已更新

之前的问题是将 `srcDir` 路径也算作了一层数据

更新后文章内 `frontmatter` 配置修改也支持刷新，还加入了本地缓存
