### ISSUE TITLE
目录都没了，空白了

### ISSUE THREAD

**Issue by elarbor** [Xaviw/vite-plugin-vitepress-auto-nav#10]
<img width="1920" alt="image" src="https://github.com/Xaviw/vite-plugin-vitepress-auto-nav/assets/43592730/1ddeaad5-d2e2-47d2-b331-8124ff502656">

# 使用插件后
<img width="1920" alt="image" src="https://github.com/Xaviw/vite-plugin-vitepress-auto-nav/assets/43592730/d6796c54-c996-4adc-a3b1-bab0e0772474">

<img width="1920" alt="image" src="https://github.com/Xaviw/vite-plugin-vitepress-auto-nav/assets/43592730/0ee63dc5-0fd0-4337-a414-1528811a28f9">

**Comment by Xaviw** [comment]
我没有发现问题怎么出现的，有复现的代码仓库吗

**Comment by chergn** [comment]
> 我没有发现问题怎么出现的，有复现的代码仓库吗

你的处理的数据结构好像不是这样的https://vitepress.dev/zh/reference/default-theme-sidebar#the-basics
[{},{},{}]这样

**Comment by Xaviw** [comment]
`sidebar` 的类型定义是：

```ts
export type Sidebar = SidebarItem[] | SidebarMulti

  export interface SidebarMulti {
    [path: string]: SidebarItem[] | { items: SidebarItem[]; base: string }
  }
```

我插件中生成的 `SidebarMulti` 格式的数据，是符合要求的
