### ISSUE TITLE
请帮我看一下配置

### ISSUE THREAD

**Issue by nicopcat** [Xaviw/vite-plugin-vitepress-auto-nav#11]
![image](https://github.com/Xaviw/vite-plugin-vitepress-auto-nav/assets/21167750/7cdfa9b6-df05-4980-8c83-24751aac8c2a)

在我理解只需要配置一个srcDir，其他都是额外配置，为什么报错了呢？

**Comment by Xaviw** [comment]
可否提供复现的仓库，这不是一个必定出现的问题，我还未能定位问题的原因

**Comment by nicopcat** [comment]
仓库地址： https://github.com/nicopcat/nicopcat.github.io
[https://opengraph.githubassets.com/d007e916b00379d74e5fd5f3bab5fc697a20b211c308d15de14158329f9341d8/nicopcat/nicopcat.github.io]<https://github.com/nicopcat/nicopcat.github.io>
GitHub - nicopcat/nicopcat.github.io<https://github.com/nicopcat/nicopcat.github.io>
Contribute to nicopcat/nicopcat.github.io development by creating an account on GitHub.
github.com

________________________________
发件人: Xavi ***@***.***>
发送时间: 2024年7月9日 2:19
收件人: Xaviw/vite-plugin-vitepress-auto-nav ***@***.***>
抄送: nekolas ***@***.***>; Author ***@***.***>
主题: Re: [Xaviw/vite-plugin-vitepress-auto-nav] 请帮我看一下配置 (Issue #11)


可否提供复现的仓库，这不是一个必定出现的问题，我还未能定位问题的原因

―

**Comment by Xaviw** [comment]
最新版本 `v2.3.3` 中已修复，问题是之前的版本中未判断文件夹名包含点 `.` 的情况
