### ISSUE TITLE
配置useArticleTitle: true不生效

### ISSUE THREAD

**Issue by yuzai-code** [Xaviw/vite-plugin-vitepress-auto-nav#13]

**Comment by Xaviw** [comment]
能否提供下复现仓库，个人没有复现出这个问题

**Comment by yuzai-code** [comment]
抱歉很久没看邮箱了。找到原因了，是我每个单个文件都配置了 title，能否将这个title移出侧边栏展示呢或者把useArticleTitle一级标题作为展示的优先级调高一点呢?，我每个文章的title都还挺长的。一级标题的useArticleTitle优先级又没有title高没办法覆盖

**Comment by Xaviw** [comment]
确实存在这个问题，我预计添加一个自定义参数前缀配置，可以通过配置避免与自身项目存在的 `frontmatter` 变量重名，解决你的问题。

至于 `useArticleTitle` 和 `title` 的优先级，个人认为还是保持现状较为合理。

等有时间了会进行更新并通知你，如果感兴趣的话也欢迎提 PR。

**Comment by Xaviw** [comment]
@yuzai-code `3.0.0` 版本已发布，新增了 `frontmatterPrefix` 配置，可以自定义配置属性名前缀，避开项目中存在的同名 `frontmatter` 变量

**配置示例：**

```ts
// config.ts
import { defineConfig } from "vitepress";
import AutoNav from "vite-plugin-vitepress-auto-nav";

export default defineConfig({
  vite: {
    plugins: [ AutoNav({ frontmatterPrefix: 'myprefix-' }) ]  
  }
})
```

```yaml
# article.md
---
title: xxx # 不会生效
myprefix-title: xxx # 生效
---
```
