### ISSUE TITLE
AutoNav 的 itemsSetting  排序好像也有点问题？

### ISSUE THREAD

**Issue by markyun** [Xaviw/vite-plugin-vitepress-auto-nav#2]
` itemsSetting: {
                    工具系列: { sort: 0 },
                    测试排序: { sort: 1 },
},`
如图，不应该工具系列 在前面吗？

实际确是  测试排序 在前面，清理缓存也没用。

**Comment by markyun** [comment]
![image](https://github.com/Xaviw/vite-plugin-vitepress-auto-nav/assets/2833137/492aecee-0ce0-41aa-9984-7160f76fe99d)

**Comment by Xaviw** [comment]
v2.2.0 已更新
