### ISSUE TITLE
更新版本后新bug， 

### ISSUE THREAD

**Issue by markyun** [Xaviw/vite-plugin-vitepress-auto-nav#3]
开启  useArticleTitle: true, // 开启使用文章一级标题作为文章名称后，点击链接会报404错

![image](https://github.com/Xaviw/vite-plugin-vitepress-auto-nav/assets/2833137/f7b30259-475a-4c64-ab4e-beebebb819f5)
![image](https://github.com/Xaviw/vite-plugin-vitepress-auto-nav/assets/2833137/13fb7376-3fc6-4d8a-9de1-8d422c5c177a)

**Comment by Xaviw** [comment]
我测试没有发现 404 的问题，有复现的仓库吗

插件还有些其他问题，今天修复

**Comment by markyun** [comment]
> 我测试没有发现 404 的问题，有复现的仓库吗
> 
> 插件还有些其他问题，今天修复

有的，我在window下，拉取代码，启动报错了

![image](https://github.com/Xaviw/vite-plugin-vitepress-auto-nav/assets/2833137/0e1f4348-64db-418e-ab8a-6d3597dab341)

**Comment by markyun** [comment]
> 我测试没有发现 404 的问题，有复现的仓库吗
> 
> 插件还有些其他问题，今天修复


奇了怪，我在GitHub部署也有同样的问题，就在刚刚

![image](https://github.com/Xaviw/vite-plugin-vitepress-auto-nav/assets/2833137/24bd2013-7ec6-4ae4-b57b-4d1d2c1b6cbd)

**Comment by Xaviw** [comment]
这是因为 cache 文件夹没有被提交到仓库，导致的报错，已经解决了。我再优化下其他问题，晚上会发布

对于你提的 404 问题，我还没有测试出来

**Comment by markyun** [comment]
> 这是因为 cache 文件夹没有被提交到仓库，导致的报错，已经解决了。我再优化下其他问题，晚上会发布
> 
> 对于你提的 404 问题，我还没有测试出来

效率很高啊，另外有一个小疑问，如果我的目录是全生成的，但我还想加一个一级目录，用来添加外部URL，该怎么做呢

如图，我想在右边添加一个自己的博客链接、作品链接。

![image](https://github.com/Xaviw/vite-plugin-vitepress-auto-nav/assets/2833137/45320db3-d2c4-4fe6-9dc5-2f5c49d02c52)

**Comment by Xaviw** [comment]
可以直接在config中自定义nav配置，存在nav配置时，插件就不会再生成

因为nav配置都比较少，我考虑到手动配置估计比在插件中传配置更容易

**Comment by markyun** [comment]
> 可以直接在config中自定义nav配置，存在nav配置时，插件就不会再生成
> 
> 因为nav配置都比较少，我考虑到手动配置估计比在插件中传配置更容易

我想能不能：在AutoNav生成结果后，再添加nav的值。

![image](https://github.com/Xaviw/vite-plugin-vitepress-auto-nav/assets/2833137/4c936a0a-1c16-42c9-9d83-e756dd539949)

**Comment by Xaviw** [comment]
是可以通过配置做到，但是配置填写的数据也不少。这样的话写插件配置和直接手写差距似乎也不大。

我想着如果开发这个功能，性价比似乎低了点

**Comment by markyun** [comment]
> 是可以通过配置做到，但是配置填写的数据也不少。这样的话写插件配置和直接手写差距似乎也不大。
> 
> 我想着如果开发这个功能，性价比似乎低了点

也行，以后有这个时间精力的时候在家吧，哈哈。

**Comment by markyun** [comment]
整体来说，目前的插件中， AutoNav 是我用过最好用的自动生成菜单数据的插件。很赞！

**Comment by Xaviw** [comment]
谢谢支持，`V2.2.1` 我发布了，同步到国内源得要一阵，晚点可以更新试下

**Comment by markyun** [comment]
> 谢谢支持，`V2.2.1` 我发布了，同步到国内源得要一阵，晚点可以更新试下

我帮你同步好了。

![image](https://github.com/Xaviw/vite-plugin-vitepress-auto-nav/assets/2833137/332a5f17-8e6c-46fd-b37f-ab41aa9aab8b)

**Comment by markyun** [comment]
> 是可以通过配置做到，但是配置填写的数据也不少。这样的话写插件配置和直接手写差距似乎也不大。
> 
> 我想着如果开发这个功能，性价比似乎低了点

这样我测试了，有一个新bug，如果手动配置l了nav，那么对应的nav 文档目录必须要有一个  index.md 文件，才能进入该一级目录，否则页面会 404.


![image](https://github.com/Xaviw/vite-plugin-vitepress-auto-nav/assets/2833137/5616d9de-e580-451e-a255-5a96b99dc1fc)

**Comment by Xaviw** [comment]
`nav` 需要配置  `link`  属性，用法可以查看[官方文档](https://vitepress.dev/zh/reference/default-theme-nav#navigation-links)。我测试没有发现问题：

```typescript
themeConfig: {
    nav: [
      {
        text: "前端系列",
        link: "前端系列/源码阅读/Axios源码解析",
        activeMatch: "/前端系列/",
      },
      {
        text: "工具系列",
        link: "工具系列/VitePress搭建/基础搭建",
        activeMatch: "/工具系列/",
      },
      {
        text: "外链",
        link: "https://github.com/Xaviw",
      },
    ],
}
```

**Comment by markyun** [comment]
> `nav` 需要配置 `link` 属性，用法可以查看[官方文档](https://vitepress.dev/zh/reference/default-theme-nav#navigation-links)。我测试没有发现问题：
> 
> ```ts
> themeConfig: {
>     nav: [
>       {
>         text: "前端系列",
>         link: "前端系列/源码阅读/Axios源码解析",
>         activeMatch: "/前端系列/",
>       },
>       {
>         text: "工具系列",
>         link: "工具系列/VitePress搭建/基础搭建",
>         activeMatch: "/工具系列/",
>       },
>       {
>         text: "外链",
>         link: "https://github.com/Xaviw",
>       },
>     ],
> }
> ```

 原来如此，也就是说   link:  必须要定位到一个具体的文档，而不能是一级目录上。

**Comment by Xaviw** [comment]
> 原来如此，也就是说 link: 必须要定位到一个具体的文档，而不能是一级目录上。

对，自己指定点击 nav 跳转到的地址，属性说明文档中都有
