### ISSUE TITLE
升级到 2.2.0后，在vercel部署时，产生了新bug

### ISSUE THREAD

**Issue by markyun** [Xaviw/vite-plugin-vitepress-auto-nav#4]
如图，build命令 提示缺少了 缓存文件夹中的文件？

![aaec05e5e8e5866c672d3ed311646c5](https://github.com/Xaviw/vite-plugin-vitepress-auto-nav/assets/2833137/fb0dc1b3-de35-4f11-9f8a-dd8d30cefcbf)

**Comment by Xaviw** [comment]
报错原因是没有判断 cache 目录是否已创建，而 cache 没有被提交到仓库中。

`V2.2.1` 中已解决
