### ISSUE TITLE
无法折叠文件

### ISSUE THREAD

**Issue by immortalts** [Xaviw/vite-plugin-vitepress-auto-nav#6]
https://github.com/immortalts/vitepress-blog，填写'HTML'也无法正常使用

**Comment by Xaviw** [comment]
那你把项目传到 github 让我看看吧

**Comment by immortalts** [comment]
> 那你把项目传到 github 让我看看吧

已设置公开

**Comment by Xaviw** [comment]
![image](https://github.com/Xaviw/vite-plugin-vitepress-auto-nav/assets/58973207/4c55b207-72ff-4809-9b93-6db863ab491d)

我下载你的项目后，pnpm 安装运行，未做任何修改，HTML 文件夹是正确折叠了的。

请确认你的问题，可以尝试删除 `node_modules`、`lock` 文件后，重新安装查看

**Comment by immortalts** [comment]
好的谢谢
