### ISSUE TITLE
使用 Markdown 格式做目录，上下页链接显示不正确

### ISSUE THREAD

**Issue by ykla** [Xaviw/vite-plugin-vitepress-auto-nav#8]
目前上下页链接一直是固定的一个。不会变，且只有下一页。

> [上下页链接 ](https://vitepress.dev/zh/reference/default-theme-prev-next-links)
>```
>如果没有在 frontmatter 中设置它，文本/链接将从侧边栏配置中推断出来。
>```

不知是哪里有问题。

目前部署在 <https://taophilosophy.github.io/>

**Comment by Xaviw** [comment]
已修复，请更新到 `v2.3.2`
