### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by meiminjun** [Xaviw/vite-plugin-vitepress-auto-nav#9]
EISDIR: illegal operation on a directory, read
Error: EISDIR: illegal operation on a directory, read

**Comment by Xaviw** [comment]
看报错信息似乎是权限相关的问题，有在其他设备测试过吗？可否提供复现项目链接

**Comment by Xaviw** [comment]
你好，我最近发现确实存在这个问题，原因是未判断文件夹名包含点 `.` 的情况，在最新的 `v2.3.3` 版本中已修复，感谢你的反馈
